window.WEDDING_CONFIG = {
  "coverHeading": "Hello You're Invited",
  "homeHeading": "The Wedding Of",
  "blessing": "Bismillahirrohmanirrohim",
  "opening0": "Assalamu’alaikum Warahmatullahi Wabarakatuh",
  "opening1": "Maha suci Allah SWT yang telah menciptakan makhluk-Nya berpasang-pasangan.",
  "opening2": "Ya Allah, perkenankanlah kami merangkai kasih sayang yang Kau ciptakan di antara putra-putri kami:",
  "brideShort": "Silfi",
  "brideName": "Silfi Sulistina",
  "brideFamily": "Putri Pertama Dari Pasangan Ibu Lailah Sumiyati & Bapak Nugi Suprasetya",
  "brideAddress": "(Link. Saksak Lurah, Kel. Kepuh, Kec. Ciwandan Kota Cilegon - Banten)",
  "bridePhoto": "img/profile/11.jpg",
  "groomShort": "Nedi",
  "groomName": "Ahmad Husnaydi",
  "groomFamily": "Putra Pertama Dari Pasangan Ibu Rohayati & Bapak Ali Yunus",
  "groomAddress": "(Kp. Buntalan, RT.017/RW.009, Desa Argawana, Kec. Pulo Ampel, Serang - Banten)",
  "groomPhoto": "img/profile/10.jpg",
  "event1Title": "Akad Nikah",
  "event1Date": "2025-06-14",
  "event1Start": "10:00",
  "event1End": "Selesai",
  "event1Place": "Mempelai Wanita",
  "event1Address": "Link. Saksak Lurah, Kel. Kepuh",
  "event1Map": "",
  "event2Title": "Resepsi",
  "event2Date": "2025-06-18",
  "event2Start": "08:30",
  "event2End": "Selesai",
  "event2Place": "Mempelai Pria",
  "event2Address": "Kp. Buntalan, RT.017/RW.009, Desa Argawana, Kec. Pulo Ampel",
  "event2Map": "https://maps.app.goo.gl/vsHY1WgTeGKBpumr6",
  "timezone": "+07:00",
  "countdownEvent": "event2",
  "gallery1": "img/gallery/7.jpg",
  "gallery2": "img/gallery/6.jpg",
  "gallery3": "img/gallery/3.jpg",
  "gallery4": "img/gallery/4.jpg",
  "gallery5": "img/gallery/2.jpg",
  "gallery6": "img/gallery/1.jpg",
  "coverImage": "img/bg/5.jpg",
  "homeImage": "img/bg/52.jpg",
  "eventImage": "img/bg/53.jpg",
  "quote": "\"Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.\"",
  "quoteSource": "QS. Ar-Rum : 21",
  "mapEmbed": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3968.3996953392166!2d106.09206730843987!3d-5.939519894020028!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e41938b7e894145%3A0xee745a929a8c9b9!2sKp.Buntalan!5e0!3m2!1sid!2sid!4v1747819737942!5m2!1sid!2sid",
  "galleryHeading": "Our Gallery",
  "countdownHeading": "Countdown",
  "eventHeading": "Save The Date",
  "rsvpHeading": "Konfirmasi Kehadiran",
  "rsvpIntro": "Mohon doa restu dan konfirmasi kehadiran Bapak/Ibu/Saudara/i.",
  "rsvpPhone": "",
  "music": "mp3/Ed-Sheeran-Perfect.mp3",
  "giftHeading": "Amplop Digital",
  "giftIntro": "Sebagai ungkapan kasih dan doa restu, Anda dapat memberikan amplop digital melalui rekening berikut:",
  "bank1Name": "Bank Mandiri",
  "bank1Owner": "Ahmad Husnaydi",
  "bank1Number": "1640005252251",
  "bank2Name": "Dana",
  "bank2Owner": "Silfi Sulistina",
  "bank2Number": "083894704373",
  "credit": "Sudahran27 | darussyifa.production",
  "footerText": "Ⓒ Website Undangan Pernikahan Online",
  "creditUrl": "",
  "siteUrl": "",
  "shareTemplate": "Assalamu’alaikum Warahmatullahi Wabarakatuh.\n\nYth. {nama}\n\nDengan penuh kebahagiaan, kami mengundang Bapak/Ibu/Saudara/i untuk menghadiri pernikahan:\n{mempelai}\n\n{tanggal}\n\nUndangan selengkapnya:\n{link}\n\nMerupakan kehormatan bagi kami atas kehadiran dan doa restunya. Terima kasih."
};
