(async()=>{
'use strict';const I=Invitation,$=id=>document.getElementById(id);let current,drafts=[],timer,dirty=false,revision=0,saving=Promise.resolve(),uploads=0;
const groups={
 couple:[['Mempelai wanita',[['brideShort','Nama panggilan *'],['brideName','Nama lengkap *'],['brideFamily','Keterangan anak & nama orang tua','textarea'],['brideAddress','Alamat keluarga','textarea']]],['Mempelai pria',[['groomShort','Nama panggilan *'],['groomName','Nama lengkap *'],['groomFamily','Keterangan anak & nama orang tua','textarea'],['groomAddress','Alamat keluarga','textarea']]]],
 events:[...['1','2'].map(n=>['Acara '+n,[['event'+n+'Title','Nama acara *'],['event'+n+'Date','Tanggal *','date'],['event'+n+'Start','Jam mulai *','time'],['event'+n+'End','Jam selesai / keterangan *'],['event'+n+'Place','Nama tempat *'],['event'+n+'Address','Alamat lengkap *','textarea'],['event'+n+'Map','Tautan Google Maps','url']]]),['Pengaturan waktu & peta',[['timezone','Zona waktu','select',[['+07:00','WIB'],['+08:00','WITA'],['+09:00','WIT']]],['countdownEvent','Acara pada sampul & hitung mundur','select',[['event1','Acara 1'],['event2','Acara 2']]],['mapEmbed','URL sematan Google Maps (opsional)','url']]]],
 media:[['Foto & latar',[['bridePhoto','Foto mempelai wanita','image'],['groomPhoto','Foto mempelai pria','image'],['coverImage','Latar sampul','image'],['homeImage','Latar halaman utama','image'],['eventImage','Latar acara','image']]],['Galeri foto',Array.from({length:6},(_,i)=>['gallery'+(i+1),'Foto galeri '+(i+1),'image'])],['Musik pengiring',[['music','Musik (MP3, M4A, OGG; maks. 15 MB)','audio']]]],
 words:[['Pembuka & judul',[['coverHeading','Sapaan sampul'],['homeHeading','Judul halaman utama'],['blessing','Kalimat pembuka'],['opening0','Salam','textarea'],['opening1','Pembuka pertama','textarea'],['opening2','Pembuka kedua','textarea'],['eventHeading','Judul acara'],['galleryHeading','Judul galeri'],['countdownHeading','Judul hitung mundur'],['quote','Kutipan / ayat','textarea'],['quoteSource','Sumber kutipan']]],['Konfirmasi WhatsApp',[['rsvpPhone','Nomor WhatsApp penerima (628…, kosong = sembunyikan)'],['rsvpHeading','Judul konfirmasi'],['rsvpIntro','Teks konfirmasi','textarea']]],['Amplop digital',[['giftHeading','Judul amplop'],['giftIntro','Pengantar amplop','textarea'],...['1','2'].flatMap(n=>[['bank'+n+'Name','Bank / dompet digital '+n],['bank'+n+'Owner','Atas nama '+n],['bank'+n+'Number','Nomor rekening '+n+' (kosong = sembunyikan)']])]],['Kredit & penutup',[['credit','Nama pembuat'],['creditUrl','Tautan pembuat (opsional)','url'],['footerText','Teks penutup']]]]
};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),6000);}
function field(spec){const [key,title,type='text',opts]=spec;const label=document.createElement('label');label.textContent=title;if(type==='textarea')label.className='full';let input=document.createElement(type==='textarea'?'textarea':type==='select'?'select':'input');input.id='f-'+key;input.dataset.key=key;input.name=key;if(type==='select'){for(const [v,t]of opts){const o=new Option(t,v);input.add(o);}}else if(type==='textarea'){input.rows=3;input.maxLength=5000;}else{input.type=['image','audio'].includes(type)?'text':type;input.maxLength=2000;}if(title.includes('*'))input.required=true;
 if(['image','audio'].includes(type)){if(type==='image'){const img=document.createElement('img');img.className='media-preview';img.id='thumb-'+key;img.alt=title;img.loading='lazy';label.append(img);}input.placeholder='Jalur file atau https://… (boleh dikosongkan)';const upload=document.createElement('input');upload.type='file';upload.className='media-input';upload.accept=type==='image'?'image/png,image/jpeg,image/webp,image/gif':'.mp3,.m4a,.ogg,.wav';upload.addEventListener('change',async()=>{const f=upload.files[0];if(!f)return;uploads++;try{if(f.size>15*1024*1024)throw Error('Ukuran maksimum 15 MB.');let data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('File tidak terbaca.'));r.readAsDataURL(f);});if(type==='image'){const img=await createImageBitmap(f);const canvas=document.createElement('canvas');const scale=Math.min(1,1800/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);data=canvas.toDataURL('image/jpeg',.86);img.close();}else if(!/^data:audio\//.test(data)){if(/\.mp3$/i.test(f.name))data=data.replace(/^data:[^;]+;/,'data:audio/mpeg;');else throw Error('Format audio tidak dikenali. Gunakan MP3.');}current.config[key]=data;input.value='';input.placeholder='File tersimpan: '+f.name;updateThumb(key);markDirty();toast('File ditambahkan. Klik Simpan draf.');}catch(e){toast(e.message);}finally{uploads--;upload.value='';}});label.append(upload);const clear=document.createElement('button');clear.type='button';clear.className='secondary';clear.textContent='Kosongkan';clear.addEventListener('click',()=>{current.config[key]='';input.value='';input.placeholder='Jalur file atau https://…';updateThumb(key);markDirty();});label.append(input,clear);}else label.append(input);
 input.addEventListener('input',()=>{current.config[key]=input.value;markDirty();updateThumb(key);});return label;}
for(const [tab,sections]of Object.entries(groups)){for(const [title,specs]of sections){const group=document.createElement('div');group.className='field-group';const h=document.createElement('h3');h.textContent=title;group.append(h);const grid=document.createElement('div');grid.className='field-grid';specs.forEach(s=>grid.append(field(s)));group.append(grid);$('fields-'+tab).append(group);}}
function setTab(tab){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.id==='tab-'+tab));document.querySelectorAll('#steps button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
document.querySelectorAll('#steps button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('config-form').onsubmit=e=>e.preventDefault();
function updateThumb(key){const img=$('thumb-'+key);if(img){const url=I.safeUrl(current.config[key],true);img.hidden=!url;if(url)img.src=url;else img.removeAttribute('src');}}
function summary(){$('couple-summary').textContent=I.couple(current.config);$('date-summary').textContent=I.date(current.config[current.config.countdownEvent+'Date']);}
function markDirty(){revision++;dirty=true;summary();$('save-status').textContent='Ada perubahan • belum disimpan';$('bottom-status').textContent='Simpan draf untuk menyimpan perubahan';}
function updateSelect(){const active=current.id;$('draft-select').replaceChildren();drafts.forEach(d=>$('draft-select').add(new Option(I.couple(d.config),d.id)));$('draft-select').value=active;}
function populate(){document.querySelectorAll('[data-key]').forEach(el=>{const v=current.config[el.dataset.key]||'';el.value=v.startsWith('data:')?'':v;if(el.id==='f-music'||$('thumb-'+el.dataset.key))el.placeholder=v.startsWith('data:')?'File unggahan tersimpan':'Jalur file atau https://…';updateThumb(el.dataset.key);});$('guest-base').value=current.config.siteUrl;$('publish-base').value=current.config.siteUrl;$('share-template').value=current.config.shareTemplate;dirty=false;$('save-status').textContent='Draf siap diedit';$('bottom-status').textContent='Perubahan publik memerlukan unggah ke GitHub';summary();updateSelect();renderGuests();}
async function save(silent=false){if(uploads)throw Error('Tunggu proses unggahan selesai.');const savedRevision=revision;const snapshot=structuredClone(current);snapshot.updatedAt=new Date().toISOString();saving=saving.catch(()=>{}).then(()=>I.storage('put',snapshot));await saving;const at=drafts.findIndex(d=>d.id===snapshot.id);if(at>=0)drafts[at]=snapshot;else drafts.push(snapshot);if(current.id===snapshot.id && revision===savedRevision){current.updatedAt=snapshot.updatedAt;dirty=false;$('save-status').textContent='Tersimpan '+new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});$('bottom-status').textContent='Draf tersimpan • belum mengubah undangan publik';updateSelect();}if(!silent)toast('Draf dan daftar tamu tersimpan di browser ini.');}
function action(id,fn){$(id).addEventListener('click',async e=>{e.preventDefault();try{await fn();}catch(err){toast(err.message||'Proses tidak berhasil.');}});}
action('save',()=>save());window.addEventListener('beforeunload',e=>{if(dirty||uploads){e.preventDefault();e.returnValue='';}});
$('draft-select').onchange=async()=>{const id=$('draft-select').value;try{if(uploads)throw Error('Tunggu unggahan selesai sebelum berpindah draf.');if(dirty)await save(true);current=structuredClone(drafts.find(d=>d.id===id));populate();}catch(e){$('draft-select').value=current.id;toast(e.message);}};
function blank(){const c=structuredClone(window.WEDDING_CONFIG);['bride','groom'].forEach(n=>{for(const suffix of ['Short','Name','Family','Address','Photo'])c[n+suffix]='';});for(const k of Object.keys(c)){if(k.startsWith('bank')||/^gallery\d/.test(k)||/^event[12](Date|Map|Place|Address)$/.test(k))c[k]='';}c.coverImage='';c.homeImage='';c.eventImage='';c.music='';c.mapEmbed='';c.siteUrl='';c.rsvpPhone='';return c;}
action('new-draft',async()=>{if(dirty)await save(true);current={id:crypto.randomUUID(),config:blank(),guests:[]};await save(true);populate();setTab('couple');toast('Draf pasangan baru dibuat. Lengkapi data dan foto Anda.');});
action('duplicate',async()=>{await save(true);current={id:crypto.randomUUID(),config:structuredClone(current.config),guests:[]};await save(true);populate();toast('Draf disalin tanpa daftar tamu. Ubah data pasangan dan alamat publiknya.');});
function setBase(v){current.config.siteUrl=v.trim();$('guest-base').value=v;$('publish-base').value=v;markDirty();}
$('guest-base').oninput=e=>setBase(e.target.value);$('publish-base').oninput=e=>setBase(e.target.value);$('share-template').oninput=e=>{current.config.shareTemplate=e.target.value;markDirty();};
function validMessage(){I.baseUrl(current.config.siteUrl);if(!current.config.shareTemplate.includes('{nama}')||!current.config.shareTemplate.includes('{link}'))throw Error('Format pesan wajib memuat {nama} dan {link}.');}
function renderGuests(){const list=$('guest-list');list.replaceChildren();$('guest-count').textContent=current.guests.length+' tamu';const query=$('search-guests').value.toLocaleLowerCase('id');const found=current.guests.filter(g=>g.name.toLocaleLowerCase('id').includes(query));if(!found.length){const p=document.createElement('p');p.className='empty';p.textContent=current.guests.length?'Nama tidak ditemukan.':'Daftar tamu belum diisi. Tambahkan satu nama per baris.';list.append(p);}
 found.forEach(g=>{const row=document.createElement('div');row.className='guest-row';const name=document.createElement('strong');name.textContent=g.name;row.append(name);const buttons=document.createElement('div');buttons.className='actions';const acts=[['Lihat',()=>{validMessage();$('message-text').textContent=I.message(current.config,g.name);$('message-preview').hidden=false;$('message-preview').scrollIntoView({behavior:'smooth',block:'center'});}],['Salin nama',async()=>{await I.copy(g.name);toast('Nama disalin.');}],['Salin link',async()=>{await I.copy(I.guestLink(current.config.siteUrl,g.name));toast('Link untuk '+g.name+' disalin.');}],['Salin pesan',async()=>{validMessage();await I.copy(I.message(current.config,g.name));toast('Pesan dan link untuk '+g.name+' disalin.');}],['Ubah',()=>{const v=prompt('Nama tamu',g.name);if(v===null)return;const trimmed=v.trim();if(!trimmed||trimmed.length>150)throw Error('Nama wajib diisi, maksimum 150 karakter.');if(current.guests.some(x=>x.id!==g.id&&x.name.toLowerCase()===trimmed.toLowerCase()))throw Error('Nama sudah ada.');g.name=trimmed;markDirty();renderGuests();}],['Hapus',()=>{if(!confirm('Hapus tamu '+g.name+'?'))return;current.guests=current.guests.filter(x=>x.id!==g.id);markDirty();renderGuests();}]];for(const [text,fn]of acts){const b=document.createElement('button');b.className='secondary'+(text==='Hapus'?' danger':'');b.textContent=text;b.onclick=async()=>{try{await fn();}catch(e){toast(e.message);}};buttons.append(b);}row.append(buttons);list.append(row);});}
$('search-guests').oninput=renderGuests;
action('add-guests',()=>{const lines=$('guest-input').value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(lines.some(n=>n.length>150))throw Error('Satu nama maksimal 150 karakter.');if(current.guests.length+lines.length>5000)throw Error('Maksimal 5.000 tamu per draf.');let count=0;const known=new Set(current.guests.map(g=>g.name.toLowerCase()));for(const name of lines){if(known.has(name.toLowerCase()))continue;known.add(name.toLowerCase());current.guests.push({id:crypto.randomUUID(),name});count++;}$('guest-input').value='';markDirty();renderGuests();toast(count+' nama ditambahkan. Nama ganda dilewati.');});
action('copy-all',async()=>{validMessage();if(!current.guests.length)throw Error('Tambahkan tamu terlebih dahulu.');await I.copy(current.guests.map(g=>I.message(current.config,g.name)).join('\n\n────────────────\n\n'));toast('Semua pesan disalin.');});
action('csv',()=>{validMessage();const cell=v=>'"'+(/^[=+@\-\t\r]/.test(v)?"'":'')+v.replace(/"/g,'""')+'"';const rows=[['Nama','Link','Pesan'],...current.guests.map(g=>[g.name,I.guestLink(current.config.siteUrl,g.name),I.message(current.config,g.name)])];I.download('daftar-tamu-pribadi.csv','\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');});
function validate(){document.querySelectorAll('.invalid').forEach(e=>e.classList.remove('invalid'));for(const el of document.querySelectorAll('[data-key]')){if(el.required&&!current.config[el.dataset.key]?.trim()){setTab(el.closest('.tab').id.slice(4));el.classList.add('invalid');el.focus();throw Error('Lengkapi isian wajib: '+el.parentElement.firstChild.textContent);}}
 for(let n=1;n<=2;n++){if(!/^\d{4}-\d{2}-\d{2}$/.test(current.config['event'+n+'Date'])||!/^\d{2}:\d{2}$/.test(current.config['event'+n+'Start']))throw Error('Tanggal dan waktu acara belum valid.');}
 for(const key of Object.keys(current.config)){const value=current.config[key];if((/Photo$|Image$|^gallery\d$|^music$/.test(key))&&value&&!I.safeUrl(value,true))throw Error('Alamat media tidak valid: '+key);if((/Map$|^creditUrl$/.test(key))&&value&&!/^https?:\/\//.test(value))throw Error('Tautan harus diawali https://: '+key);}
 if(current.config.mapEmbed){const u=new URL(current.config.mapEmbed);if(!['https:'].includes(u.protocol)||! /^(www\.)?google\.(com|co\.id)$/.test(u.hostname)||!u.pathname.startsWith('/maps'))throw Error('Peta sematan harus berupa URL https://www.google.com/maps/embed…');}
 if(current.config.rsvpPhone&&!/^62\d{8,13}$/.test(current.config.rsvpPhone))throw Error('Nomor WhatsApp gunakan 62 diikuti nomor, tanpa spasi. Contoh 628123456789.');
}
async function preview(){validate();await save(true);window.open('index.html?preview='+encodeURIComponent(current.id)+'&to='+encodeURIComponent('Bapak Ahmad & Ibu Siti'),'_blank','noopener');}
action('preview',preview);action('preview-publish',preview);
action('backup',async()=>{await save(true);I.download('cadangan-undangan-pribadi.json',JSON.stringify({format:'invitation-studio',version:1,draft:current},null,2),'application/json');});
$('restore').onchange=async()=>{try{if(uploads)throw Error('Tunggu unggahan selesai.');const f=$('restore').files[0];if(!f)return;if(f.size>90*1024*1024)throw Error('Cadangan terlalu besar.');const data=JSON.parse(await f.text());if(data.format!=='invitation-studio'||data.version!==1||typeof data.draft?.config!=='object'||!Array.isArray(data.draft?.guests))throw Error('Berkas bukan cadangan undangan yang didukung.');if(data.draft.guests.length>5000)throw Error('Maksimal 5.000 tamu.');if(dirty)await save(true);const guests=data.draft.guests.map(g=>{if(typeof g.name!=='string'||!g.name.trim()||g.name.length>150)throw Error('Nama tamu dalam cadangan tidak valid.');return{id:crypto.randomUUID(),name:g.name.trim()};});current={id:crypto.randomUUID(),config:I.normalize(data.draft.config),guests};await save(true);populate();toast('Cadangan diimpor sebagai draf baru.');}catch(e){toast(e.message);}finally{$('restore').value='';}};
action('export',async()=>{validate();I.baseUrl(current.config.siteUrl);await save(true);const button=$('export');button.disabled=true;try{const config=structuredClone(current.config),entries=[],stamp=Date.now();for(const [key,val]of Object.entries(config)){if(/^data:(image|audio)\//.test(val)){const match=val.match(/^data:([^;]+);base64,(.+)$/s);if(!match)throw Error('Media rusak: '+key);const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','audio/mpeg':'mp3','audio/mp3':'mp3','audio/mp4':'m4a','audio/x-m4a':'m4a','audio/ogg':'ogg','audio/wav':'wav','audio/x-wav':'wav'}[match[1]];if(!ext)throw Error('Format media belum didukung: '+match[1]);const path='media/'+key+'-'+stamp+'.'+ext;entries.push([path,Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0))]);config[key]=path;}}
 const doc=new DOMParser().parseFromString(window.INVITATION_TEMPLATE,'text/html');doc.title=I.couple(config)+' | Undangan Pernikahan';for(const [prop,value]of Object.entries({'og:title':doc.title,'og:description':I.date(config[config.countdownEvent+'Date'])+' — Kami mengundang Anda untuk hadir dalam momen bahagia kami.','og:url':I.baseUrl(config.siteUrl).href,'og:image':config.coverImage?new URL(config.coverImage,I.baseUrl(config.siteUrl)).href:''})){doc.querySelector('meta[property="'+prop+'"]').content=value;}
 // Bake all personalized content so no previous couple's names remain in the HTML.
 doc.querySelectorAll('[data-text]').forEach(e=>e.textContent=config[e.dataset.text]||'');doc.querySelectorAll('[data-couple]').forEach(e=>e.textContent=I.couple(config));doc.querySelectorAll('[data-date]').forEach(e=>e.textContent=I.date(config[config.countdownEvent+'Date']));doc.querySelectorAll('[data-src]').forEach(e=>{if(config[e.dataset.src])e.setAttribute('src',config[e.dataset.src]);else e.removeAttribute('src');});doc.querySelectorAll('[data-bg]').forEach(e=>e.style.backgroundImage=config[e.dataset.bg]?'url('+JSON.stringify(config[e.dataset.bg])+')':'none');doc.querySelector('[data-map-embed]').setAttribute('src',config.mapEmbed||'about:blank');doc.querySelectorAll('[data-event-map]').forEach(e=>e.href=config[e.dataset.eventMap+'Map']||'#');doc.querySelector('.map [data-main-map]').setAttribute('href',config[config.countdownEvent+'Map']||'#');
 entries.unshift(['index.html','<!doctype html>\n'+doc.documentElement.outerHTML],['data.js','window.WEDDING_CONFIG = '+JSON.stringify(config,null,2).replace(/</g,'\\u003c')+';\n']);entries.push(['.nojekyll','']);
 I.download('pembaruan-undangan.zip',makeZip(entries),'application/zip');$('export-status').textContent='Paket dibuat '+new Date().toLocaleString('id-ID')+'. Ekstrak lalu unggah seluruh isinya ke repository yang sudah berisi paket utama.';toast('Paket pembaruan siap. Unggah isinya ke GitHub untuk menerbitkan.');
 }finally{button.disabled=false;}});
try{drafts=await I.storage('getAll');if(!drafts.length){current={id:crypto.randomUUID(),config:structuredClone(window.WEDDING_CONFIG),guests:[]};await save(true);}else{drafts.sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));current=structuredClone(drafts[0]);current.config=I.normalize(current.config);}populate();}catch(e){$('save-status').textContent='Penyimpanan tidak tersedia';$('bottom-status').textContent='Buka pada browser biasa dengan penyimpanan diaktifkan.';toast('Penyimpanan browser tidak tersedia. Gunakan localhost / GitHub Pages dan aktifkan penyimpanan situs.');}
})();
